[package]
name = "iso-rs"
version.workspace = true
edition.workspace = true

[dependencies]
bitflags = { version = "2.9.0", features = ["bytemuck"] }
bytemuck = { version = "1.22.0", features = ["derive"] }
chrono = "0.4.40"

[dev-dependencies]
static_assertions = "1.1.0"
