[workspace]
resolver = "2"
members = ["crates/iso-cli", "crates/iso-rs"]
default-members = ["crates/iso-cli", "crates/iso-rs"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
iso-rs = { path = "crates/iso-rs", version = "0.1.0" }
