[package]
name = "iso-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { version = "2.9.0", features = ["bytemuck"] }
bytemuck = { version = "1.22.0", features = ["derive"] }
chrono = "0.4.40"
